root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["serve", "--http=127.0.0.1:8090"]
  bin = "./tmp/main"
  cmd = "templ generate && npx @tailwindcss/cli -i tailwind.css -o pb_public/css/main.css && go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "pb_data", "pb_public/css"]
  exclude_file = []
  exclude_regex = ["_test.go", "_templ.go", ".*\\.css$"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = [".", "pb_public", "templates"]
  include_ext = ["go", "tpl", "tmpl", "html", "templ", "js"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
