// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.937
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// UserMenu component that displays either a login button or user avatar with dropdown
func UserMenu() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- User Menu / Login Button --><div class=\"user-menu\"><!-- Login Button when not logged in --><button x-show=\"!user\" @click=\"$dispatch('open-modal', 'login-modal')\" class=\"btn\">Login</button><!-- User Avatar Menu when logged in --><div x-show=\"user\" x-cloak><div x-data=\"{ open: false }\" @click.outside=\"open = false\"><div @click=\"open = !open\"><img x-show=\"user && user.avatar\" :src=\"pb.files.getURL(user, user.avatar, { thumb: '40x40' })\" :alt=\"user?.name || user?.email\" class=\"avatar\"><div x-show=\"!user || !user.avatar\" class=\"avatar-placeholder\" x-text=\"userInitial\"></div></div><div x-show=\"open\" x-transition:enter=\"transition ease-out duration-100\" x-transition:enter-start=\"transform opacity-0 scale-95\" x-transition:enter-end=\"transform opacity-100 scale-100\" x-transition:leave=\"transition ease-in duration-75\" x-transition:leave-start=\"transform opacity-100 scale-100\" x-transition:leave-end=\"transform opacity-0 scale-95\" class=\"dropdown-menu\" x-cloak><div class=\"user-info\"><strong x-text=\"user?.name || 'User'\"></strong><p x-text=\"user?.email\"></p></div><hr><a href=\"/settings\">Settings</a><hr><button @click=\"logout()\">Logout</button></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
